# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    branches:
      only:
        - master

    docker:
      # specify the version you desire here
      - image: circleci/node:11.6.0
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:

      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      # let's install npm
      - run: npm install --silent
      # install angular cli latest globally
      - run: sudo npm install -g @angular/cli@latest --silent
      # update 
      - run: npm update
      # switch to using production URL
      - run: sed -i "/const uri = 'http:\/\/localhost:1337\/graphql';/c\const uri = 'https:\/\/api.khophi.photography\/graphql';" ./src/app/graphql.module.ts
      # ng build --prod
      - run: ng build --prod

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # copy dist files to digitalocean
      - run: scp -o StrictHostKeyChecking=no -r ./dist/Photog/* khophi@khophi.com://home/khophi/khophi.photography/

      ################ WARNING WARNING #####################
      # doing no strict host key check is a security rist to some extent.
      # But I haven't figured a way to add to ssh for both CI and DO to communicate without that
      # message popping up 
